### PR TITLE
Enforce array for some XML nodes

### LINKED ISSUE #13: Enforcing JSON ARRAY for some XML nodes
If an array with a single value is serialized into XML and then converted into JSON it stops being an array and becomes a value or an object. Then it fails to deserialize into `Vec` or any other collection type. Examples:

```xml
<a>
    <b>1</b>
    <b>2</b>
</a>
```
becomes 
```json
"a": {
    "b": [1,2]
}
```
and can be deserialized into `Vec<i64>`, but
```xml
<a>
    <b>1</b>
</a>
```
becomes 
```json
"a": {
    "b": 1
}
```
and fails if we try to put it into the same `Vec<i64>` type.

## Proposed solution

1. Add `JsonType::Array` to enforce an array on the mapped XML elements the same way we enforce other types 
2. Allow mixing `JsonType::Array` with other types, e.g. `JsonType::AlwaysString` so that 
```xml
<a>
    <b>1</b>
</a>
```
becomes 
```json
"a": { "b": [1] }
```
with `Infer` or
```json
"a": { "b": ["1"] }
```
with `AlwaysString`

3. This will be an extension to recently merged type enforcement, which is an optional feature and will affect existing implementations.

@AlecTroemel , Alec, do you have a minute to review this? Does it make sense? Am I on the right path here?

### PR DESCRIPTION
**Pull request by rimutaka**
Closes #13 

## Changes

1. Bumped the version to 0.4.3
2. Updated ReadMe with examples and explanations
3. Added built-in tests

## Breaking changes

* Added `JsonArray` enum to specify if a node should always be an array

Specifying the JSON type is a 2-level enum. 

It used to be just `JsonType::AlwaysString`. Now the type has to be wrapped into `JsonArray` like this: `JsonArray::Infer(JsonType::AlwaysString))`

**Before**:
```rust
let conf = Config::new_with_defaults()
        .add_json_type_override("/a/@attr1", JsonType::AlwaysString)
        .add_json_type_override("/a/b/@attr1", JsonType::AlwaysString)
        .add_json_type_override("/a/b", JsonType::AlwaysString);
```

**After**:
```rust
    let conf = Config::new_with_defaults()
        .add_json_type_override("/a/@attr1", JsonArray::Infer(JsonType::AlwaysString))
        .add_json_type_override("/a/b/@attr1", JsonArray::Infer(JsonType::AlwaysString))
        .add_json_type_override("/a/b", JsonArray::Infer(JsonType::AlwaysString));
```

It's not a big change. I fixed the existing code with a single global search and replace.

## Testing

Apart from the built-in tests it has been running in PROD for a couple of weeks.

@AlecTroemel , Alec, please, take a look if you have a minute.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -354,3 +375,26 @@ pub fn xml_string_to_json(xml: String, config: &Config) -> Result<Value, Error>
     let root = Element::from_str(xml.as_str())?;
     Ok(xml_to_map(&root, config))
 }
+
+/// Returns a tuple for Array and Value enforcements for the current node or
+/// `(false, JsonArray::Infer(JsonType::Infer)` if the current path is not found
+/// in the list of paths with custom config.
+#[cfg(feature = "json_types")]
+#[inline]
```
Comment (AlecTroemel) [inline src/lib.rs:383]: whats the thought for explicitly calling out inline here? From [the docs](https://doc.rust-lang.org/reference/attributes/codegen.html?highlight=inline#the-inline-attribute), it seems like the compiler will already inline where it feels is right

Comment (rimutaka) [reply src/lib.rs:383]: It's a small function called from within a FOR LOOP. I thought it would be less stack pushing if it's inlined. Do you see a problem?

Comment (AlecTroemel) [reply src/lib.rs:383]: no not necessarily, I've just never explicitly used `#[inline]` :laughing:  

since the attribute is a _suggestion_ to the compiler, and you have a good reason for the suggestion, I'm fine leaving it in

**Comment by AlecTroemel** [comment]
LGTM!
